# Generated by /u-deploy (v{{pluginVersion}}) — target: docker
# App: {{appName}}
# Gatekeeping docScore at generation: {{docScore}} / 100
#
# Re-running /u-deploy regenerates this Dockerfile if SSoT docs change.
# To preserve manual edits, wrap them in `# KEEP-START … # KEEP-END` blocks.

FROM {{baseImage}} AS builder
WORKDIR /app
COPY . .
RUN {{installCmd}}
RUN {{buildCmd}}

FROM {{runtimeImage}}
WORKDIR /app
COPY --from=builder /app/{{distDir}} ./{{distDir}}
{{#if hasPackageFile}}
COPY --from=builder /app/{{packageFile}} ./{{packageFile}}
RUN {{prodInstallCmd}}
{{/if}}

ENV NODE_ENV=production
# Secrets come from runtime env (set by orchestrator), not baked in.

EXPOSE {{port}}

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD curl -fsS http://localhost:{{port}}{{healthPath}} || exit 1

CMD [{{cmdArray}}]
